pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  trigger_website_build:
    stage: deploy
    trigger:
      project: axos-project/axos-project.gitlab.io
      branch: main
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
