name: Deploy AxOS Mirrors to Cloudflare R2

on:
  workflow_run:
    workflows: ["Update mirrors"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Updated Repository
        uses: actions/download-artifact@v4
        with:
          name: updated-repo
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync repository to Cloudflare R2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'axmirrors'
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          AWS_REGION: 'auto'
          SOURCE_DIR: './'