name: Update mirrors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          pacman -Sy --noconfirm pacman-contrib binutils python git

      - name: Run update.sh
        run: |
          cd ./x86_64
          chmod +x update.sh
          ./update.sh

      - name: Upload Repository Artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-repo
          path: |
            ./*
            !./.git