name: Update mirrors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run update.sh
        run: ./x86_64/update.sh

      - name: Run autogen.py
        run: python3 ./autogen.py
